# Generated by Django 4.1.2 on 2022-12-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costomuser',
            name='parent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
