# Generated by Django 4.1.2 on 2022-12-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0003_remove_department_description_department_adresss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='creater',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
