# Generated by Django 4.1.2 on 2022-12-10 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0004_department_creater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muddat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muddat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Arizalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pasport_seria', models.CharField(blank=True, max_length=10, null=True)),
                ('data_user', models.CharField(blank=True, max_length=50, null=True)),
                ('pasport_photo', models.FileField(blank=True, null=True, upload_to='photo/pasport')),
                ('code_pasport', models.CharField(blank=True, max_length=255, null=True)),
                ('summa_limet', models.CharField(blank=True, max_length=255, null=True)),
                ('selfe_photo', models.FileField(blank=True, null=True, upload_to='photo/selfi/')),
                ('maxshulot_summasi', models.CharField(blank=True, max_length=255, null=True)),
                ('yechiladigon_summa', models.CharField(blank=True, max_length=255, null=True)),
                ('shartnoma_asli', models.FileField(blank=True, null=True, upload_to='photo/Shartnoma_asli/')),
                ('shantnoma_imzo', models.FileField(blank=True, null=True, upload_to='photo/shantnoma_imzo/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.department')),
                ('type_muddat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.muddat')),
            ],
        ),
    ]
