# Generated by Django 4.1.2 on 2022-12-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0012_arizalar_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='costomuser',
            name='is_operator',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
