# Generated by Django 4.1.2 on 2022-12-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0015_alter_arizalar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizalar',
            name='commet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
