# Generated by Django 4.1.2 on 2022-12-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0017_rename_shantnoma_imzo_arizalar_shantnoma_imzo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizalar',
            name='chek_photo',
            field=models.FileField(blank=True, null=True, upload_to='photo/shantnoma_imzo/'),
        ),
        migrations.AlterField(
            model_name='arizalar',
            name='shantnoma_imzo1',
            field=models.FileField(blank=True, null=True, upload_to='photo/shantnoma_imzo2/'),
        ),
        migrations.AlterField(
            model_name='arizalar',
            name='shartnoma_asli1',
            field=models.FileField(blank=True, null=True, upload_to='photo/Shartnoma_asli1/'),
        ),
        migrations.AlterField(
            model_name='arizalar',
            name='shartnoma_asli2',
            field=models.FileField(blank=True, null=True, upload_to='photo/Shartnoma_asli2/'),
        ),
        migrations.AlterField(
            model_name='arizalar',
            name='status',
            field=models.CharField(blank=True, choices=[('Новый', 'Новый '), ('Рассматривается', 'Рассматривается'), ('Qaytish', 'Qaytish'), ('SMS', 'SMS'), ('Одобрено', 'Одобрено '), ('Отказано', 'Отказано '), ('Karta', 'Karta'), ('Оформлено', 'Оформлено '), ('Отменено', 'Отменено  ')], default='Новый', max_length=50, null=True),
        ),
    ]
