# Generated by Django 4.1.2 on 2022-12-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0019_alter_arizalar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizalar',
            name='shantnoma_imzo2',
            field=models.FileField(blank=True, null=True, upload_to='photo/shantnoma_imzo2/'),
        ),
        migrations.AlterField(
            model_name='arizalar',
            name='shantnoma_imzo1',
            field=models.FileField(blank=True, null=True, upload_to='photo/shantnoma_imzo1/'),
        ),
        migrations.AlterField(
            model_name='arizalar',
            name='status',
            field=models.CharField(blank=True, choices=[('Новый', 'Новый '), ('Рассматривается', 'Рассматривается'), ('Qaytish', 'Qaytish'), ('SMS', 'SMS'), ('SMS_send', 'SMS_send'), ('Одобрено', 'Одобрено '), ('Отказано', 'Отказано '), ('Karta', 'Karta'), ('Оформлено', 'Оформлено '), ('Shartnoma', 'Shartnoma '), ('Отменено', 'Отменено  ')], default='Новый', max_length=50, null=True),
        ),
    ]
